### ISSUE TITLE
Unavailable entity climate.smoker

### ISSUE THREAD

**Issue by Jackald1918** [pdugas/recteq#12]
Synology 918+:

https://imgur.com/G14OJzo
https://imgur.com/Btwsa4h
https://imgur.com/Fu6DBjF

Verified tuya keys, uninstalled / reinstalled several times. 

Logger: custom_components.recteq.device
Source: custom_components/recteq/device.py:127
Integration: Recteq (documentation, issues)
First occurred: 10:11:50 PM (7 occurrences)
Last logged: 10:12:50 PM

Unexpected error fetching Smoker data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/recteq/device.py", line 145, in _async_update_data
    await self.async_update()
  File "/config/custom_components/recteq/device.py", line 140, in async_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/recteq/device.py", line 127, in update
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 311, in status
    result = json.loads(result)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Supervisor Core Logs
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 311, in status
    result = json.loads(result)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-12-23 22:26:41 DEBUG (MainThread) [custom_components.recteq.device] Finished fetching Smoker data in 0.025 seconds
2020-12-23 22:26:41 INFO (SyncWorker_16) [somecomfort] Session refreshed
2020-12-23 22:26:51 DEBUG (SyncWorker_2) [pytuya] status() entry
2020-12-23 22:26:51 DEBUG (SyncWorker_2) [pytuya] json_payload=b'{"gwId":"18345033bcddc296d94f","devId":"18345033bcddc296d94f"}'
2020-12-23 22:26:51 DEBUG (SyncWorker_2) [pytuya] status received data=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00,\x00\x00\x00\x01\x19G\x99\x06\x88\x0b\xec\xd9\xf9w\x0e\x02\x13b\xd4\xef\xd4\xb7>\xff\xe9V\xb1\xc7Jo\xe4+\xd5\x8czk\xd2\t\xe7S\x00\x00\xaaU'
2020-12-23 22:26:51 DEBUG (SyncWorker_2) [pytuya] result=b'\x19G\x99\x06\x88\x0b\xec\xd9\xf9w\x0e\x02\x13b\xd4\xef\xd4\xb7>\xff\xe9V\xb1\xc7Jo\xe4+\xd5\x8czk'
2020-12-23 22:26:51 DEBUG (SyncWorker_2) [pytuya] decrypted result=''
2020-12-23 22:26:51 ERROR (MainThread) [custom_components.recteq.device] Unexpected error fetching Smoker data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/recteq/device.py", line 145, in _async_update_data
    await self.async_update()
  File "/config/custom_components/recteq/device.py", line 140, in async_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/recteq/device.py", line 127, in update
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 311, in status
    result = json.loads(result)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-12-23 22:26:51 DEBUG (MainThread) [custom_components.recteq.device] Finished fetching Smoker data in 0.028 seconds
2020-12-23 22:27:01 DEBUG (SyncWorker_3) [pytuya] status() entry
2020-12-23 22:27:01 DEBUG (SyncWorker_3) [pytuya] json_payload=b'{"gwId":"18345033bcddc296d94f","devId":"18345033bcddc296d94f"}'
2020-12-23 22:27:01 DEBUG (SyncWorker_3) [pytuya] status received data=b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00,\x00\x00\x00\x01\x19G\x99\x06\x88\x0b\xec\xd9\xf9w\x0e\x02\x13b\xd4\xef\xd4\xb7>\xff\xe9V\xb1\xc7Jo\xe4+\xd5\x8czk\xd2\t\xe7S\x00\x00\xaaU'
2020-12-23 22:27:01 DEBUG (SyncWorker_3) [pytuya] result=b'\x19G\x99\x06\x88\x0b\xec\xd9\xf9w\x0e\x02\x13b\xd4\xef\xd4\xb7>\xff\xe9V\xb1\xc7Jo\xe4+\xd5\x8czk'
2020-12-23 22:27:01 DEBUG (SyncWorker_3) [pytuya] decrypted result=''
2020-12-23 22:27:01 ERROR (MainThread) [custom_components.recteq.device] Unexpected error fetching Smoker data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/recteq/device.py", line 145, in _async_update_data
    await self.async_update()
  File "/config/custom_components/recteq/device.py", line 140, in async_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/recteq/device.py", line 127, in update
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 311, in status
    result = json.loads(result)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-12-23 22:27:01 DEBUG (MainThread) [custom_components.recteq.device] Finished fetching Smoker data in 0.029 seconds
2020-12-23 22:27:06 ERROR (MainThread) [custom_components.hacs] Error trying to serve custom_components/spotcast/
Traceback (most recent call last):
  File "/config/custom_components/hacs/webresponses/category.py", line 22, in async_serve_category_file
    response = await async_serve_static_file_with_etag(
  File "/config/custom_components/hacs/webresponses/category.py", line 52, in async_serve_static_file_with_etag
    etag = await async_get_etag(servefile)
  File "/config/custom_components/hacs/helpers/functions/file_etag.py", line 18, in async_get_etag
    fnv = await hass.async_add_executor_job(get_etag, path)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hacs/helpers/functions/file_etag.py", line 13, in get_etag
    return fnv1a_32(file_path.read_bytes())
  File "/usr/local/lib/python3.8/pathlib.py", line 1228, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/local/lib/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
IsADirectoryError: [Errno 21] Is a directory: '/config/www/community/custom_components/spotcast'
2020-12-23 22:27:06 ERROR (MainThread) [custom_components.hacs] Error trying to serve custom_components/unifigateway/
Traceback (most recent call last):
  File "/config/custom_components/hacs/webresponses/category.py", line 22, in async_serve_category_file
    response = await async_serve_static_file_with_etag(
  File "/config/custom_components/hacs/webresponses/category.py", line 52, in async_serve_static_file_with_etag
    etag = await async_get_etag(servefile)
  File "/config/custom_components/hacs/helpers/functions/file_etag.py", line 18, in async_get_etag
    fnv = await hass.async_add_executor_job(get_etag, path)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hacs/helpers/functions/file_etag.py", line 13, in get_etag
    return fnv1a_32(file_path.read_bytes())
  File "/usr/local/lib/python3.8/pathlib.py", line 1228, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/local/lib/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,[](url)

**Comment by pdugas** [comment]
Will look at this soon.  Sorry for the delay.

**Comment by Jackald1918** [comment]
No worries, thanks for the update and the time u  and others spent getting
this to work!!
Jim Davis

**Comment by pdugas** [comment]
I'm not sure what's going on to generate that error. Gotta admit I'm no expert on HA's inner workings. I have a fully current instance of HA with this plugin installed and it's not producing that error. Maybe I'll try using incorrect configs and see if that causes this.

**Comment by Jackald1918** [comment]
Don't put much time into it, I often have more issues with using the
synology in docker, sometimes, not always someone with a Synology has the
same issue and I can follow what they did to get it to work.
Thanks, again
Jim Davis

**Comment by trplowman** [comment]
I had this integration working but recently had to reinstall Ubuntu on the computer that I use for my home assistant server which is installed as a virtual machine. On the previous setup home assistant was running as a VM using VirtualBox, but this time I am using the virtual machine software that comes with Ubuntu and setup my home assistant using the KVM file. Cannot get my recteq smoker to work now, just shows as unavailable no matter how many ways I have tried to install/re-install this integration. 

Below is the info from the log:

2021-06-22 17:20:12 ERROR (MainThread) [custom_components.recteq.device] Unexpected error fetching Smoker data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/recteq/device.py", line 135, in _async_update_data
    await self.async_update()
  File "/config/custom_components/recteq/device.py", line 130, in async_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/recteq/device.py", line 117, in update
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 311, in status
    result = json.loads(result)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Jackald1918** [comment]
Just got home assistant blue odroid n2+ and am having the same issue as above. Wish I had tried to install before installing most of my setup from scratch to see if something else was interfering with install. trplowman, please let us know if you were able to resolve. Thanks

**Comment by trplowman** [comment]
Nope, unable to get it working.

Sent from my iPhone

On Jun 29, 2021, at 2:39 PM, Jackald1918 ***@***.***> wrote:

﻿

Just got home assistant blue odroid n2+ and am having the same issue as above. Wish I had tried to install before installing most of my setup from scratch to see if something else was interfering with install. trplowman, please let us know if you were able to resolve. Thanks
