### ISSUE TITLE
Unavailable

### ISSUE THREAD

**Issue by trplowman** [pdugas/recteq#17]
Had to reinstall my Home Assistant and when I tried to setup this integration it will install but my grill just shows as "unavailable". Was working on my previous installation of Home Assistant, not sure why it won't now. Below is the info from the log.

2021-07-10 12:39:45 DEBUG (SyncWorker_1) [pytuya] decrypted result=''
2021-07-10 12:39:45 ERROR (MainThread) [custom_components.recteq.device] Unexpected error fetching Wilbur data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/recteq/device.py", line 145, in _async_update_data
    await self.async_update()
  File "/config/custom_components/recteq/device.py", line 140, in async_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/recteq/device.py", line 127, in update
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.9/site-packages/pytuya/__init__.py", line 311, in status
    result = json.loads(result)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-07-10 12:39:45 DEBUG (MainThread) [custom_components.recteq.device] Finished fetching Wilbur data in 0.207 seconds

**Comment by pdugas** [comment]
Hi @trplowman. I have to admit that my Python and HA foo is lacking here. I don't see anything in that dump that suggests to me anything other than maybe it didn't get the expected response. You may want to head over to the HA forums and ask there. Sorry.

**Comment by JamesHabben** [comment]
@trplowman do you have the right version number? 3.1 vs 3.3

I have an rt-700 and it gave me a similar response when I incorrectly used version 3.3

**Comment by trplowman** [comment]
I tried both, neither worked for me. Haven’t tried it again lately.

Sent from my iPhone

On Jul 30, 2021, at 4:59 PM, James Habben ***@***.***> wrote:

﻿

@trplowman<https://github.com/trplowman> do you have the right version number? 3.1 vs 3.3

I have an rt-700 and it gave me a similar response when I incorrectly used version 3.3

**Comment by Jackald1918** [comment]
I have an rt-700 also,  and it gave me a same  response from a fresh install
