### ISSUE TITLE
Integration loads, all entities unavailable

### ISSUE THREAD

**Issue by Jackald1918** [pdugas/recteq#21]
I had posted in the past,  I could never get the integration to run. Tried every conceivable option I could think of. Current running on Home Assistant Blue and upon boot with a fresh install, could not get it to work. Starting to think something in the controller is kaput or the stars won't align. The errors remain the same, entities are all unavailable. Open to any ideas or possible solutions. Thanks.

File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/recteq/device.py", line 145, in _async_update_data
await self.async_update()
File "/config/custom_components/recteq/device.py", line 140, in async_update
await self.hass.async_add_executor_job(self.update)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/recteq/device.py", line 127, in update
self._cached_status = self._pytuya.status()['dps']
File "/usr/local/lib/python3.9/site-packages/pytuya/__init__.py", line 311, in status
result = json.loads(result)
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-08-22 16:43:20 ERROR (MainThread) [custom_components.recteq.device] Unexpected error fetching Smoker data: Expecting value: line 1 column 1 (char 0)

**Comment by ethan-holland** [comment]
Just a quick thought, if the smoker is off the entities all appear as unavailable. You may need to load the integration (everything appears unavailable) and then turn on the smoker (everything shows up) and then when you turn it off the power button would be available from that point on. This seems to have been my experience when I loaded this yesterday. Hope it helps!

**Comment by Jackald1918** [comment]
Thanks for the info, will go back and reload and see if I didn't try it with the power button on. I think I did, however, will go back and reload. Will be sure and give feedback to the results.

**Comment by Jackald1918** [comment]
Same Issue as before setup on Home Assistant Blue, latest updates: 
Logger: custom_components.recteq.device
Source: custom_components/recteq/device.py:127
Integration: Recteq (documentation, issues)
First occurred: 10:10:31 PM (6 occurrences)
Last logged: 10:11:23 PM

Unexpected error fetching The-Bull data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/recteq/device.py", line 145, in _async_update_data
    await self.async_update()
  File "/config/custom_components/recteq/device.py", line 140, in async_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/recteq/device.py", line 127, in update
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.9/site-packages/pytuya/__init__.py", line 311, in status
    result = json.loads(result)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
